<?php

define("UPS_USERID","JoeBot");				  #Set your ups  User Id here
define("UPS_PASSWORD","Dojob1289");				  #Set your ups Password here
define("UPS_API_KEY" ,"DC6EB9BFBAB1DDB0");

define("UPS_COMPANYNAME","B&B Charcoal");
define("UPS_ATTENTIONNAME","");
define("UPS_SHIPPERNUMBER","0Y032A");

define("UPS_CREDITCARDTYPE","06");
define("UPS_CREDITCARDNUMBER","4635720008311845");
define("UPS_CREDITCARDEXPIRATION","0114");

define("UPS_ADDRESSLINE1","4710 Jeddo Rd");
define("UPS_ADDRESSCITY","Flatonia");
define("UPS_ADDRESSSTATE","TX");
define("UPS_ADDRESSPOSTAL","78941");

define("UPS_PICKUPEARLIEST","0945");
define("UPS_PICKUPLATEST","1445");
define("UPS_CONTACTNAME","TravisKainer");
define("UPS_CONTACTPHONE","3618653444");

$GLOBALS["SHIPPING"]["LARGE_BOXLENGTH"] = 24;
$GLOBALS["SHIPPING"]["LARGE_BOXWIDTH"] = 18;
$GLOBALS["SHIPPING"]["LARGE_BOXHEIGHT"] = 18;
$GLOBALS["SHIPPING"]["LARGE_WEIGHTPERBOX"] = 60;

$GLOBALS["SHIPPING"]["MID_BOXLENGTH"] = 24;
$GLOBALS["SHIPPING"]["MID_BOXWIDTH"] = 18;
$GLOBALS["SHIPPING"]["MID_BOXHEIGHT"] = 6;
$GLOBALS["SHIPPING"]["MID_WEIGHTPERBOX"] = 22;

$GLOBALS["SHIPPING"]["SMALL_BOXLENGTH"] = 18;
$GLOBALS["SHIPPING"]["SMALL_BOXWIDTH"] = 12;
$GLOBALS["SHIPPING"]["SMALL_BOXHEIGHT"] = 6;
$GLOBALS["SHIPPING"]["SMALL_WEIGHTPERBOX"] = 12;

define("UPS_WEIGHTMAXWEIGHT",150);
?>